#!/usr/bin/env python3
"""
Read the model-availability-report.json and write src/data/model-availability.ts
"""

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
REPORT_PATH = PROJECT_ROOT / "catalog" / "model-availability-report.json"
OUTPUT_PATH = PROJECT_ROOT / "src" / "data" / "model-availability.ts"

with open(REPORT_PATH) as f:
    all_data = json.load(f)

lines = []
lines.append('/**')
lines.append(' * Static lookup of which 3D models (GLBs) are available per series.')
lines.append(' *')
lines.append(' * Generated by scripts/convert-dwg/03-gen-availability.py')
lines.append(' * from GLB filenames in catalog/glb/{Series}/.')
lines.append(' *')
lines.append(' * Storage path: {seriesCode}/{filename} in Supabase Storage bucket "models".')
lines.append(' *')
lines.append(' * When a shape+size+base combo is NOT in this map, the configurator should')
lines.append(' * show "model not available" instead of attempting to load a missing file.')
lines.append(' */')
lines.append('')
lines.append('export interface ShapeAvailability {')
lines.append('  sizes: string[];')
lines.append('  bases: string[];')
lines.append('}')
lines.append('')
lines.append('export interface SeriesAvailability {')
lines.append('  shapes: Record<string, ShapeAvailability>;')
lines.append('  defaultGlb: string;')
lines.append('}')
lines.append('')
lines.append('export const MODEL_AVAILABILITY: Record<string, SeriesAvailability> = {')

for data in all_data:
    code = data["series_code"]
    name = data["series_name"]
    total = data["total_glbs"]
    shapes = data["shapes"]
    default_glb = data["default_glb"]

    lines.append(f'  // {name} (series {code}) — {total} GLBs, {len(shapes)} shapes')
    lines.append(f'  "{code}": {{')
    lines.append(f'    shapes: {{')

    for shape_name, info in shapes.items():
        sizes = info["sizes"]
        bases = info["bases"]
        lines.append(f'      {shape_name}: {{')

        if len(sizes) <= 5:
            sizes_str = ", ".join(f'"{s}"' for s in sizes)
            lines.append(f'        sizes: [{sizes_str}],')
        else:
            lines.append(f'        sizes: [')
            for i in range(0, len(sizes), 7):
                chunk = sizes[i:i+7]
                chunk_str = ", ".join(f'"{s}"' for s in chunk)
                lines.append(f'          {chunk_str},')
            lines.append(f'        ],')

        bases_str = ", ".join(f'"{b}"' for b in bases)
        lines.append(f'        bases: [{bases_str}],')
        lines.append(f'      }},')

    lines.append(f'    }},')
    lines.append(f'    defaultGlb: "{default_glb}",')
    lines.append(f'  }},')
    lines.append('')

lines.append('};')
lines.append('')

# GLB_FILENAMES section
lines.append('/**')
lines.append(' * GLB filename lookup: series -> "SHAPE|SIZE|BASE" -> filename.')
lines.append(' *')
lines.append(' * Because base widths vary per series and aren\'t derivable from a simple formula,')
lines.append(' * we store the exact filenames here instead of computing them at runtime.')
lines.append(' */')
lines.append('export const GLB_FILENAMES: Record<string, Record<string, string>> = {')

for data in all_data:
    code = data["series_code"]
    filenames = data["filenames"]
    lines.append(f'  "{code}": {{')
    for key, filename in filenames.items():
        lines.append(f'    "{key}": "{filename}",')
    lines.append(f'  }},')
    lines.append('')

lines.append('};')
lines.append('')

# Helper functions
lines.append('''/**
 * Look up the exact GLB filename for a series + shape + size + base combo.
 * Returns null if no model exists for that combination.
 */
export function lookupGlbFilename(
  seriesCode: string,
  shape: string,
  size: string,
  base: string,
): string | null {
  const seriesLookup = GLB_FILENAMES[seriesCode];
  if (!seriesLookup) return null;
  const key = `${shape.toUpperCase()}|${size}|${base.toUpperCase()}`;
  return seriesLookup[key] ?? null;
}

/**
 * Get shapes available for a series from the model availability map.
 */
export function getAvailableShapes(seriesCode: string): string[] {
  const series = MODEL_AVAILABILITY[seriesCode];
  if (!series) return [];
  return Object.keys(series.shapes);
}

/**
 * Get sizes available for a specific series + shape combo.
 */
export function getAvailableSizes(seriesCode: string, shapeCode: string): string[] {
  const series = MODEL_AVAILABILITY[seriesCode];
  if (!series) return [];
  return series.shapes[shapeCode]?.sizes ?? [];
}

/**
 * Get bases available for a specific series + shape combo.
 */
export function getAvailableBases(seriesCode: string, shapeCode: string): string[] {
  const series = MODEL_AVAILABILITY[seriesCode];
  if (!series) return [];
  return series.shapes[shapeCode]?.bases ?? [];
}

/**
 * Get the default hero GLB filename for a series.
 */
export function getDefaultGlb(seriesCode: string): string | undefined {
  return MODEL_AVAILABILITY[seriesCode]?.defaultGlb;
}

/**
 * Format a raw size code into a human-readable label.
 *
 * Rectangular sizes: "3060" -> '30" x 60"'
 * Round sizes (1-2 digits): "48" -> '48" Round'
 * Long tables (5 digits): "42120" -> '42" x 120"'
 * Wedge/special: "45d36" -> '45" x D36"'
 */
export function formatSizeLabel(raw: string): string {
  // Wedge-style sizes with "d" separator
  if (raw.includes("d")) {
    const parts = raw.split("d");
    return `${parts[0]}" x D${parts[1]}"`;
  }

  // Round tables (1-2 digit = just diameter)
  if (raw.length <= 2) {
    return `${raw}" Round`;
  }

  // 5-digit sizes: first 2 = width, rest = length (e.g., "42120" -> 42 x 120)
  if (raw.length === 5) {
    const w = raw.substring(0, 2);
    const l = raw.substring(2);
    return `${w}" x ${l}"`;
  }

  // Standard 4-digit: first 2 = width, last 2 = length
  if (raw.length === 4) {
    const w = raw.substring(0, 2);
    const l = raw.substring(2);
    return `${w}" x ${l}"`;
  }

  return raw;
}''')

with open(OUTPUT_PATH, "w") as f:
    f.write("\n".join(lines) + "\n")

total_models = sum(d["total_glbs"] for d in all_data)
total_filenames = sum(len(d["filenames"]) for d in all_data)
print(f"Written {OUTPUT_PATH}")
print(f"  {len(all_data)} series, {total_models} models, {total_filenames} filename entries")
