/**
 * Static lookup of which 3D models (GLBs) are available per series.
 *
 * Generated by parsing the GLB filenames in catalog/glb/{Series}/.
 * Naming convention: {shape}{size}{base}{baseWidth}.glb (all lowercase).
 *
 * When a shape+size+base combo is NOT in this map, the configurator should
 * show "model not available" instead of attempting to load a missing file.
 */

export interface ShapeAvailability {
  sizes: string[];
  bases: string[];
}

export interface SeriesAvailability {
  shapes: Record<string, ShapeAvailability>;
  defaultGlb: string;
}

export const MODEL_AVAILABILITY: Record<string, SeriesAvailability> = {
  // Ultra (series 00) — 81 GLBs, 5 shapes, U-Leg base only
  "00": {
    shapes: {
      TC: {
        sizes: [
          "2036", "2048", "2060", "2072", "2084", "2090", "2096",
          "2436", "2448", "2460", "2472", "2484", "2490", "2496",
          "3036", "3048", "3060", "3072", "3084", "3090", "3096",
          "3648", "3660", "3672", "3684", "3690", "3696",
          "4260", "4272", "4284", "4290", "4296",
          "4860", "4872", "4884", "4890", "4896",
          "42120", "42144", "48120", "48144",
        ],
        bases: ["U"],
      },
      D: {
        sizes: [
          "2436", "2448", "2460", "2472", "2484", "2490", "2496",
          "3048", "3060", "3072", "3084", "3090", "3096",
          "3648", "3660", "3672", "3684", "3690", "3696",
          "4272", "4284", "4290", "4296",
          "4872", "4884", "4890", "4896",
        ],
        bases: ["U"],
      },
      BT: {
        sizes: [
          "3084", "3090", "3096",
          "3684", "3690", "3696",
          "36120", "36144",
        ],
        bases: ["U"],
      },
      RD: {
        sizes: ["48", "54", "60"],
        bases: ["U"],
      },
      TA: {
        sizes: ["3760", "4278"],
        bases: ["U"],
      },
    },
    defaultGlb: "tc3060u28.glb",
  },

  // Foundation (series 30) — 309 GLBs, 22 shapes, multiple base types
  "30": {
    shapes: {
      TC: {
        sizes: [
          "1836", "1848", "1860", "1872", "1884", "1890", "1896",
          "2036", "2048", "2060", "2072", "2084", "2090", "2096",
          "2436", "2448", "2460", "2472", "2484", "2490", "2496",
          "3036", "3048", "3060", "3072", "3084", "3090", "3096",
          "3648", "3660", "3672", "3684", "3690", "3696",
          "4260", "4272", "4284", "4290", "4296",
          "4860", "4872", "4884", "4890", "4896",
          "42120", "42144", "48120", "48144",
        ],
        bases: ["T", "TT"],
      },
      D: {
        sizes: [
          "2436", "2448", "2460", "2472", "2484", "2490", "2496",
          "3048", "3060", "3072", "3084", "3090", "3096",
          "3648", "3660", "3672", "3684", "3690", "3696",
          "4260", "4272", "4284", "4290", "4296",
          "4860", "4872", "4884", "4890", "4896",
          "5454", "6060",
        ],
        bases: ["T", "TT", "X"],
      },
      BT: {
        sizes: [
          "3084", "3090", "3096",
          "3684", "3690", "3696",
          "36120", "36144",
        ],
        bases: ["T", "TT"],
      },
      EL: {
        sizes: [
          "3054", "3060",
          "3660", "3672", "3684", "3690", "3696",
          "4272", "4284", "4290", "4296",
          "4872", "4884", "4890", "4896",
          "42120", "42144", "48120", "48144",
        ],
        bases: ["T", "TT"],
      },
      RT: {
        sizes: [
          "3660", "3672", "3684", "3690", "3696",
          "4284", "4290", "4296",
          "4884", "4890", "4896",
          "42120", "42144", "48120", "48144",
        ],
        bases: ["T", "TT"],
      },
      RD: {
        sizes: ["24", "30", "36", "42", "48", "54", "60"],
        bases: ["TT", "X"],
      },
      SQ: {
        sizes: ["2424", "3030", "3636", "4242", "4848", "5454", "6060"],
        bases: ["TT", "X"],
      },
      SL: {
        sizes: ["24", "30", "36", "42", "48"],
        bases: ["X"],
      },
      BU: {
        sizes: ["2418", "3020", "3624", "4230", "4836"],
        bases: ["X"],
      },
      TZ: {
        sizes: ["2448", "2472", "3060", "3672"],
        bases: ["T"],
      },
      VW: {
        sizes: ["2040", "2448", "3060", "3672"],
        bases: ["T"],
      },
      HR: {
        sizes: ["1836", "2448", "3060", "3672"],
        bases: ["T"],
      },
      AS: {
        sizes: ["2044", "2451", "3059", "3667"],
        bases: ["T"],
      },
      TN: {
        sizes: ["2030", "2430", "3030", "3630"],
        bases: ["T"],
      },
      TA: {
        sizes: ["3760", "4278"],
        bases: ["T"],
      },
      CR: {
        sizes: ["2442", "3048"],
        bases: ["T"],
      },
      CS: {
        sizes: ["2475", "2494", "3094"],
        bases: ["T"],
      },
      TR: {
        sizes: ["4020", "4824", "6030"],
        bases: ["TOS"],
      },
      QD: {
        sizes: ["6018", "6020", "6024", "6030"],
        bases: ["X"],
      },
      QR: {
        sizes: ["3030", "3636"],
        bases: ["GNT"],
      },
      WG: {
        sizes: ["45d36", "60d30", "60d36"],
        bases: ["GNT"],
      },
      TE: {
        sizes: ["2448"],
        bases: ["X"],
      },
    },
    defaultGlb: "tc3060t26.glb",
  },

  // Fundamental (series 33) — 309 GLBs, 22 shapes, multiple base types
  "33": {
    shapes: {
      TC: {
        sizes: [
          "1836", "1848", "1860", "1872", "1884", "1890", "1896",
          "2036", "2048", "2060", "2072", "2084", "2090", "2096",
          "2436", "2448", "2460", "2472", "2484", "2490", "2496",
          "3036", "3048", "3060", "3072", "3084", "3090", "3096",
          "3648", "3660", "3672", "3684", "3690", "3696",
          "4260", "4272", "4284", "4290", "4296",
          "4860", "4872", "4884", "4890", "4896",
          "42120", "42144", "48120", "48144",
        ],
        bases: ["T", "TT"],
      },
      D: {
        sizes: [
          "2436", "2448", "2460", "2472", "2484", "2490", "2496",
          "3048", "3060", "3072", "3084", "3090", "3096",
          "3648", "3660", "3672", "3684", "3690", "3696",
          "4260", "4272", "4284", "4290", "4296",
          "4860", "4872", "4884", "4890", "4896",
          "5454", "6060",
        ],
        bases: ["T", "TT", "X"],
      },
      BT: {
        sizes: [
          "3084", "3090", "3096",
          "3684", "3690", "3696",
          "36120", "36144",
        ],
        bases: ["T", "TT"],
      },
      EL: {
        sizes: [
          "3054", "3060",
          "3660", "3672", "3684", "3690", "3696",
          "4272", "4284", "4290", "4296",
          "4872", "4884", "4890", "4896",
          "42120", "42144", "48120", "48144",
        ],
        bases: ["T", "TT"],
      },
      RT: {
        sizes: [
          "3660", "3672", "3684", "3690", "3696",
          "4284", "4290", "4296",
          "4884", "4890", "4896",
          "42120", "42144", "48120", "48144",
        ],
        bases: ["T", "TT"],
      },
      RD: {
        sizes: ["24", "30", "36", "42", "48", "54", "60"],
        bases: ["TT", "X"],
      },
      SQ: {
        sizes: ["2424", "3030", "3636", "4242", "4848", "5454", "6060"],
        bases: ["TT", "X"],
      },
      SL: {
        sizes: ["24", "30", "36", "42", "48"],
        bases: ["X"],
      },
      BU: {
        sizes: ["2418", "3020", "3624", "4230", "4836"],
        bases: ["X"],
      },
      TZ: {
        sizes: ["2448", "2472", "3060", "3672"],
        bases: ["T"],
      },
      VW: {
        sizes: ["2040", "2448", "3060", "3672"],
        bases: ["T"],
      },
      HR: {
        sizes: ["1836", "2448", "3060", "3672"],
        bases: ["T"],
      },
      AS: {
        sizes: ["2044", "2451", "3059", "3667"],
        bases: ["T"],
      },
      TN: {
        sizes: ["2030", "2430", "3030", "3630"],
        bases: ["T"],
      },
      TA: {
        sizes: ["3760", "4278"],
        bases: ["T"],
      },
      CR: {
        sizes: ["2442", "3048"],
        bases: ["T"],
      },
      CS: {
        sizes: ["2475", "2494", "3094"],
        bases: ["T"],
      },
      TR: {
        sizes: ["4020", "4824", "6030"],
        bases: ["TOS"],
      },
      QD: {
        sizes: ["6018", "6020", "6024", "6030"],
        bases: ["X"],
      },
      QR: {
        sizes: ["3030", "3636"],
        bases: ["GNT"],
      },
      WG: {
        sizes: ["45d36", "60d30", "60d36"],
        bases: ["GNT"],
      },
      TE: {
        sizes: ["2448"],
        bases: ["X"],
      },
    },
    defaultGlb: "tc3060t26.glb",
  },
};

/**
 * GLB filename lookup: series -> "SHAPE|SIZE|BASE" -> filename.
 *
 * Because base widths vary per series and aren't derivable from a simple formula
 * (Ultra uses width-2, Foundation varies by base type and width), we store the
 * exact filenames here instead of computing them at runtime.
 */
export const GLB_FILENAMES: Record<string, Record<string, string>> = {
  "00": {
    "BT|3084|U": "bt3084u28.glb",
    "BT|3090|U": "bt3090u28.glb",
    "BT|3096|U": "bt3096u28.glb",
    "BT|36120|U": "bt36120u34u18.glb",
    "BT|36144|U": "bt36144u34u18.glb",
    "BT|3684|U": "bt3684u34.glb",
    "BT|3690|U": "bt3690u34.glb",
    "BT|3696|U": "bt3696u34.glb",
    "D|2436|U": "d2436u22.glb",
    "D|2448|U": "d2448u22.glb",
    "D|2460|U": "d2460u22.glb",
    "D|2472|U": "d2472u22.glb",
    "D|2484|U": "d2484u22.glb",
    "D|2490|U": "d2490u22.glb",
    "D|2496|U": "d2496u22.glb",
    "D|3048|U": "d3048u28.glb",
    "D|3060|U": "d3060u28.glb",
    "D|3072|U": "d3072u28.glb",
    "D|3084|U": "d3084u28.glb",
    "D|3090|U": "d3090u28.glb",
    "D|3096|U": "d3096u28.glb",
    "D|3648|U": "d3648u34.glb",
    "D|3660|U": "d3660u34.glb",
    "D|3672|U": "d3672u34.glb",
    "D|3684|U": "d3684u34.glb",
    "D|3690|U": "d3690u34.glb",
    "D|3696|U": "d3696u34.glb",
    "D|4272|U": "d4272u40.glb",
    "D|4284|U": "d4284u40.glb",
    "D|4290|U": "d4290u40.glb",
    "D|4296|U": "d4296u40.glb",
    "D|4872|U": "d4872u46.glb",
    "D|4884|U": "d4884u46.glb",
    "D|4890|U": "d4890u46.glb",
    "D|4896|U": "d4896u46.glb",
    "RD|48|U": "rd48u18-4.glb",
    "RD|54|U": "rd54u18-4.glb",
    "RD|60|U": "rd60u18-4.glb",
    "TA|3760|U": "ta3760u34.glb",
    "TA|4278|U": "ta4278u40.glb",
    "TC|2036|U": "tc2036u18.glb",
    "TC|2048|U": "tc2048u18.glb",
    "TC|2060|U": "tc2060u18.glb",
    "TC|2072|U": "tc2072u18.glb",
    "TC|2084|U": "tc2084u18.glb",
    "TC|2090|U": "tc2090u18.glb",
    "TC|2096|U": "tc2096u18.glb",
    "TC|2436|U": "tc2436u22.glb",
    "TC|2448|U": "tc2448u22.glb",
    "TC|2460|U": "tc2460u22.glb",
    "TC|2472|U": "tc2472u22.glb",
    "TC|2484|U": "tc2484u22.glb",
    "TC|2490|U": "tc2490u22.glb",
    "TC|2496|U": "tc2496u22.glb",
    "TC|3036|U": "tc3036u28.glb",
    "TC|3048|U": "tc3048u28.glb",
    "TC|3060|U": "tc3060u28.glb",
    "TC|3072|U": "tc3072u28.glb",
    "TC|3084|U": "tc3084u28.glb",
    "TC|3090|U": "tc3090u28.glb",
    "TC|3096|U": "tc3096u28.glb",
    "TC|3648|U": "tc3648u34.glb",
    "TC|3660|U": "tc3660u34.glb",
    "TC|3672|U": "tc3672u34.glb",
    "TC|3684|U": "tc3684u34.glb",
    "TC|3690|U": "tc3690u34.glb",
    "TC|3696|U": "tc3696u34.glb",
    "TC|42120|U": "tc42120u40u18.glb",
    "TC|42144|U": "tc42144u40u18.glb",
    "TC|4260|U": "tc4260u40.glb",
    "TC|4272|U": "tc4272u40.glb",
    "TC|4284|U": "tc4284u40.glb",
    "TC|4290|U": "tc4290u40.glb",
    "TC|4296|U": "tc4296u40.glb",
    "TC|48120|U": "tc48120u46u18.glb",
    "TC|48144|U": "tc48144u46u18.glb",
    "TC|4860|U": "tc4860u46.glb",
    "TC|4872|U": "tc4872u46.glb",
    "TC|4884|U": "tc4884u46.glb",
    "TC|4890|U": "tc4890u46.glb",
    "TC|4896|U": "tc4896u46.glb",
  },
  "30": {
    "AS|2044|T": "as2044t18.glb",
    "AS|2451|T": "as2451t20.glb",
    "AS|3059|T": "as3059t26.glb",
    "AS|3667|T": "as3667t26.glb",
    "BT|3084|T": "bt3084t26.glb",
    "BT|3090|T": "bt3090t26.glb",
    "BT|3096|T": "bt3096t26.glb",
    "BT|36120|TT": "bt36120tt36-3.glb",
    "BT|36144|TT": "bt36144tt36-3.glb",
    "BT|3684|TT": "bt3684tt34.glb",
    "BT|3690|TT": "bt3690tt34.glb",
    "BT|3696|TT": "bt3696tt34.glb",
    "BU|2418|X": "bu2418x22.glb",
    "BU|3020|X": "bu3020x26.glb",
    "BU|3624|X": "bu3624x30.glb",
    "BU|4230|X": "bu4230x32.glb",
    "BU|4836|X": "bu4836x36.glb",
    "CR|2442|T": "cr2442t30.glb",
    "CR|3048|T": "cr3048t36.glb",
    "CS|2475|T": "cs2475t22.glb",
    "CS|2494|T": "cs2494t22.glb",
    "CS|3094|T": "cs3094t26.glb",
    "D|2436|T": "d2436t20.glb",
    "D|2448|T": "d2448t20.glb",
    "D|2460|T": "d2460t20.glb",
    "D|2472|T": "d2472t20.glb",
    "D|2484|T": "d2484t20.glb",
    "D|2490|T": "d2490t20.glb",
    "D|2496|T": "d2496t20.glb",
    "D|3048|T": "d3048t26.glb",
    "D|3060|T": "d3060t26.glb",
    "D|3072|T": "d3072t26.glb",
    "D|3084|T": "d3084t26.glb",
    "D|3090|T": "d3090t26.glb",
    "D|3096|T": "d3096t26.glb",
    "D|3648|T": "d3648t26.glb",
    "D|3660|T": "d3660t26.glb",
    "D|3672|T": "d3672t26.glb",
    "D|3684|T": "d3684t26.glb",
    "D|3690|T": "d3690t26.glb",
    "D|3696|T": "d3696t26.glb",
    "D|4260|TT": "d4260tt34.glb",
    "D|4272|TT": "d4272tt34.glb",
    "D|4284|TT": "d4284tt34.glb",
    "D|4290|TT": "d4290tt34.glb",
    "D|4296|TT": "d4296tt34.glb",
    "D|4860|TT": "d4860tt36.glb",
    "D|4872|TT": "d4872tt36.glb",
    "D|4884|TT": "d4884tt36.glb",
    "D|4890|TT": "d4890tt36.glb",
    "D|4896|TT": "d4896tt36.glb",
    "D|5454|X": "d5454x36.4.glb",
    "D|6060|X": "d6060x42.4.glb",
    "EL|3054|T": "el3054t22.glb",
    "EL|3060|T": "el3060t22.glb",
    "EL|3660|T": "el3660t26.glb",
    "EL|3672|T": "el3672t26.glb",
    "EL|3684|T": "el3684t26.glb",
    "EL|3690|T": "el3690t26.glb",
    "EL|3696|T": "el3696t26.glb",
    "EL|42120|TT": "el42120tt303430.glb",
    "EL|42144|TT": "el42144tt303430.glb",
    "EL|4272|TT": "el4272tt26.glb",
    "EL|4284|TT": "el4284tt26.glb",
    "EL|4290|TT": "el4290tt26.glb",
    "EL|4296|TT": "el4296tt26.glb",
    "EL|48120|TT": "el48120tt303630.glb",
    "EL|48144|TT": "el48144tt303630.glb",
    "EL|4872|TT": "el4872tt30.glb",
    "EL|4884|TT": "el4884tt30.glb",
    "EL|4890|TT": "el4890tt30.glb",
    "EL|4896|TT": "el4896tt30.glb",
    "HR|1836|T": "hr1836t16.glb",
    "HR|2448|T": "hr2448t16.glb",
    "HR|3060|T": "hr3060t20.glb",
    "HR|3672|T": "hr3672t26.glb",
    "QD|6018|X": "qd6018x36.4.glb",
    "QD|6020|X": "qd6020x36.4.glb",
    "QD|6024|X": "qd6024x36.4.glb",
    "QD|6030|X": "qd6030x36.4.glb",
    "QR|3030|GNT": "qr3030gnt20.glb",
    "QR|3636|GNT": "qr3636gnt20.glb",
    "RD|24|X": "rd24x22.glb",
    "RD|30|X": "rd30x26.glb",
    "RD|36|X": "rd36x30.glb",
    "RD|42|X": "rd42x32.glb",
    "RD|48|TT": "rd48tt26.glb",
    "RD|48|X": "rd48x36.glb",
    "RD|54|TT": "rd54tt30.glb",
    "RD|54|X": "rd54x32.4.glb",
    "RD|60|TT": "rd60tt34.glb",
    "RD|60|X": "rd60x36.4.glb",
    "RT|3660|T": "rt3660t26.glb",
    "RT|3672|T": "rt3672t26.glb",
    "RT|3684|T": "rt3684t26.glb",
    "RT|3690|T": "rt3690t26.glb",
    "RT|3696|T": "rt3696t26.glb",
    "RT|42120|TT": "rt42120tt34-3.glb",
    "RT|42144|TT": "rt42144tt34-3.glb",
    "RT|4284|TT": "rt4284tt34.glb",
    "RT|4290|TT": "rt4290tt34.glb",
    "RT|4296|TT": "rt4296tt34.glb",
    "RT|48120|TT": "rt48120tt36-3.glb",
    "RT|48144|TT": "rt48144tt36-3.glb",
    "RT|4884|TT": "rt4884tt34.glb",
    "RT|4890|TT": "rt4890tt34.glb",
    "RT|4896|TT": "rt4896tt34.glb",
    "SL|24|X": "sl24x22.glb",
    "SL|30|X": "sl30x26.glb",
    "SL|36|X": "sl36x32.glb",
    "SL|42|X": "sl42x36.glb",
    "SL|48|X": "sl48x38.glb",
    "SQ|2424|X": "sq2424x22.glb",
    "SQ|3030|X": "sq3030x26.glb",
    "SQ|3636|X": "sq3636x32.glb",
    "SQ|4242|X": "sq4242x36.glb",
    "SQ|4848|TT": "sq4848tt34.glb",
    "SQ|4848|X": "sq4848x38.glb",
    "SQ|5454|X": "sq5454x36.4.glb",
    "SQ|6060|X": "sq6060x42.4.glb",
    "TA|3760|T": "ta3760t26.glb",
    "TA|4278|T": "ta4278t30.glb",
    "TC|1836|T": "tc1836t16.glb",
    "TC|1848|T": "tc1848t16.glb",
    "TC|1860|T": "tc1860t16.glb",
    "TC|1872|T": "tc1872t16.glb",
    "TC|1884|T": "tc1884t16.glb",
    "TC|1890|T": "tc1890t16.glb",
    "TC|1896|T": "tc1896t16.glb",
    "TC|2036|T": "tc2036t18.glb",
    "TC|2048|T": "tc2048t18.glb",
    "TC|2060|T": "tc2060t18.glb",
    "TC|2072|T": "tc2072t18.glb",
    "TC|2084|T": "tc2084t18.glb",
    "TC|2090|T": "tc2090t18.glb",
    "TC|2096|T": "tc2096t18.glb",
    "TC|2436|T": "tc2436t20.glb",
    "TC|2448|T": "tc2448t20.glb",
    "TC|2460|T": "tc2460t20.glb",
    "TC|2472|T": "tc2472t20.glb",
    "TC|2484|T": "tc2484t20.glb",
    "TC|2490|T": "tc2490t20.glb",
    "TC|2496|T": "tc2496t20.glb",
    "TC|3036|T": "tc3036t26.glb",
    "TC|3048|T": "tc3048t26.glb",
    "TC|3060|T": "tc3060t26.glb",
    "TC|3072|T": "tc3072t26.glb",
    "TC|3084|T": "tc3084t26.glb",
    "TC|3090|T": "tc3090t26.glb",
    "TC|3096|T": "tc3096t26.glb",
    "TC|3648|T": "tc3648t26.glb",
    "TC|3660|T": "tc3660t26.glb",
    "TC|3672|T": "tc3672t26.glb",
    "TC|3684|T": "tc3684t26.glb",
    "TC|3690|T": "tc3690t26.glb",
    "TC|3696|T": "tc3696t26.glb",
    "TC|42120|TT": "tc42120tt34-3.glb",
    "TC|42144|TT": "tc42144tt34-3.glb",
    "TC|4260|TT": "tc4260tt34.glb",
    "TC|4272|TT": "tc4272tt34.glb",
    "TC|4284|TT": "tc4284tt34.glb",
    "TC|4290|TT": "tc4290tt34.glb",
    "TC|4296|TT": "tc4296tt34.glb",
    "TC|48120|TT": "tc48120tt36-3.glb",
    "TC|48144|TT": "tc48144tt36-3.glb",
    "TC|4860|TT": "tc4860tt36.glb",
    "TC|4872|TT": "tc4872tt36.glb",
    "TC|4884|TT": "tc4884tt36.glb",
    "TC|4890|TT": "tc4890tt36.glb",
    "TC|4896|TT": "tc4896tt36.glb",
    "TE|2448|X": "te2448x3236.glb",
    "TN|2030|T": "tn2030t18.glb",
    "TN|2430|T": "tn2430t20.glb",
    "TN|3030|T": "tn3030t26.glb",
    "TN|3630|T": "tn3630t26.glb",
    "TR|4020|TOS": "tr4020tos16-3.glb",
    "TR|4824|TOS": "tr4824tos16-3.glb",
    "TR|6030|TOS": "tr6030tos16-3.glb",
    "TZ|2448|T": "tz2448t18.glb",
    "TZ|2472|T": "tz2472t18.glb",
    "TZ|3060|T": "tz3060t22.glb",
    "TZ|3672|T": "tz3672t26.glb",
    "VW|2040|T": "vw2040t18.glb",
    "VW|2448|T": "vw2448t20.glb",
    "VW|3060|T": "vw3060t26.glb",
    "VW|3672|T": "vw3672t26.glb",
    "WG|45d36|GNT": "wg45d36gnt20.glb",
    "WG|60d30|GNT": "wg60d30gnt20.glb",
    "WG|60d36|GNT": "wg60d36gnt20.glb",
  },
  "33": {
    "AS|2044|T": "as2044t18.glb",
    "AS|2451|T": "as2451t20.glb",
    "AS|3059|T": "as3059t26.glb",
    "AS|3667|T": "as3667t26.glb",
    "BT|3084|T": "bt3084t26.glb",
    "BT|3090|T": "bt3090t26.glb",
    "BT|3096|T": "bt3096t26.glb",
    "BT|36120|TT": "bt36120tt36-3.glb",
    "BT|36144|TT": "bt36144tt36-3.glb",
    "BT|3684|TT": "bt3684tt34.glb",
    "BT|3690|TT": "bt3690tt34.glb",
    "BT|3696|TT": "bt3696tt34.glb",
    "BU|2418|X": "bu2418x22.glb",
    "BU|3020|X": "bu3020x26.glb",
    "BU|3624|X": "bu3624x30.glb",
    "BU|4230|X": "bu4230x32.glb",
    "BU|4836|X": "bu4836x36.glb",
    "CR|2442|T": "cr2442t30.glb",
    "CR|3048|T": "cr3048t36.glb",
    "CS|2475|T": "cs2475t22.glb",
    "CS|2494|T": "cs2494t22.glb",
    "CS|3094|T": "cs3094t26.glb",
    "D|2436|T": "d2436t20.glb",
    "D|2448|T": "d2448t20.glb",
    "D|2460|T": "d2460t20.glb",
    "D|2472|T": "d2472t20.glb",
    "D|2484|T": "d2484t20.glb",
    "D|2490|T": "d2490t20.glb",
    "D|2496|T": "d2496t20.glb",
    "D|3048|T": "d3048t26.glb",
    "D|3060|T": "d3060t26.glb",
    "D|3072|T": "d3072t26.glb",
    "D|3084|T": "d3084t26.glb",
    "D|3090|T": "d3090t26.glb",
    "D|3096|T": "d3096t26.glb",
    "D|3648|T": "d3648t26.glb",
    "D|3660|T": "d3660t26.glb",
    "D|3672|T": "d3672t26.glb",
    "D|3684|T": "d3684t26.glb",
    "D|3690|T": "d3690t26.glb",
    "D|3696|T": "d3696t26.glb",
    "D|4260|TT": "d4260tt34.glb",
    "D|4272|TT": "d4272tt34.glb",
    "D|4284|TT": "d4284tt34.glb",
    "D|4290|TT": "d4290tt34.glb",
    "D|4296|TT": "d4296tt34.glb",
    "D|4860|TT": "d4860tt36.glb",
    "D|4872|TT": "d4872tt36.glb",
    "D|4884|TT": "d4884tt36.glb",
    "D|4890|TT": "d4890tt36.glb",
    "D|4896|TT": "d4896tt36.glb",
    "D|5454|X": "d5454x36.4.glb",
    "D|6060|X": "d6060x42.4.glb",
    "EL|3054|T": "el3054t22.glb",
    "EL|3060|T": "el3060t22.glb",
    "EL|3660|T": "el3660t26.glb",
    "EL|3672|T": "el3672t26.glb",
    "EL|3684|T": "el3684t26.glb",
    "EL|3690|T": "el3690t26.glb",
    "EL|3696|T": "el3696t26.glb",
    "EL|42120|TT": "el42120tt303430.glb",
    "EL|42144|TT": "el42144tt303430.glb",
    "EL|4272|TT": "el4272tt26.glb",
    "EL|4284|TT": "el4284tt26.glb",
    "EL|4290|TT": "el4290tt26.glb",
    "EL|4296|TT": "el4296tt26.glb",
    "EL|48120|TT": "el48120tt303630.glb",
    "EL|48144|TT": "el48144tt303630.glb",
    "EL|4872|TT": "el4872tt30.glb",
    "EL|4884|TT": "el4884tt30.glb",
    "EL|4890|TT": "el4890tt30.glb",
    "EL|4896|TT": "el4896tt30.glb",
    "HR|1836|T": "hr1836t16.glb",
    "HR|2448|T": "hr2448t16.glb",
    "HR|3060|T": "hr3060t20.glb",
    "HR|3672|T": "hr3672t26.glb",
    "QD|6018|X": "qd6018x36-4.glb",
    "QD|6020|X": "qd6020x36-4.glb",
    "QD|6024|X": "qd6024x36-4.glb",
    "QD|6030|X": "qd6030x36-4.glb",
    "QR|3030|GNT": "qr3030gnt20.glb",
    "QR|3636|GNT": "qr3636gnt20.glb",
    "RD|24|X": "rd24x22.glb",
    "RD|30|X": "rd30x26.glb",
    "RD|36|X": "rd36x30.glb",
    "RD|42|X": "rd42x32.glb",
    "RD|48|TT": "rd48tt26.glb",
    "RD|48|X": "rd48x36.glb",
    "RD|54|TT": "rd54tt30.glb",
    "RD|54|X": "rd54x32.4.glb",
    "RD|60|TT": "rd60tt34.glb",
    "RD|60|X": "rd60x36.4.glb",
    "RT|3660|T": "rt3660t26.glb",
    "RT|3672|T": "rt3672t26.glb",
    "RT|3684|T": "rt3684t26.glb",
    "RT|3690|T": "rt3690t26.glb",
    "RT|3696|T": "rt3696t26.glb",
    "RT|42120|TT": "rt42120tt34-3.glb",
    "RT|42144|TT": "rt42144tt34-3.glb",
    "RT|4284|TT": "rt4284tt34.glb",
    "RT|4290|TT": "rt4290tt34.glb",
    "RT|4296|TT": "rt4296tt34.glb",
    "RT|48120|TT": "rt48120tt34-3.glb",
    "RT|48144|TT": "rt48144tt34-3.glb",
    "RT|4884|TT": "rt4884tt34.glb",
    "RT|4890|TT": "rt4890tt34.glb",
    "RT|4896|TT": "rt4896tt34.glb",
    "SL|24|X": "sl24x22.glb",
    "SL|30|X": "sl30x26.glb",
    "SL|36|X": "sl36x32.glb",
    "SL|42|X": "sl42x36.glb",
    "SL|48|X": "sl48x38.glb",
    "SQ|2424|X": "sq2424x22.glb",
    "SQ|3030|X": "sq3030x26.glb",
    "SQ|3636|X": "sq3636x32.glb",
    "SQ|4242|X": "sq4242x36.glb",
    "SQ|4848|TT": "sq4848tt34.glb",
    "SQ|4848|X": "sq4848x38.glb",
    "SQ|5454|X": "sq5454x36.4.glb",
    "SQ|6060|X": "sq6060x42.4.glb",
    "TA|3760|T": "ta3760t26.glb",
    "TA|4278|T": "ta4278t30.glb",
    "TC|1836|T": "tc1836t16.glb",
    "TC|1848|T": "tc1848t16.glb",
    "TC|1860|T": "tc1860t16.glb",
    "TC|1872|T": "tc1872t16.glb",
    "TC|1884|T": "tc1884t16.glb",
    "TC|1890|T": "tc1890t16.glb",
    "TC|1896|T": "tc1896t16.glb",
    "TC|2036|T": "tc2036t18.glb",
    "TC|2048|T": "tc2048t18.glb",
    "TC|2060|T": "tc2060t18.glb",
    "TC|2072|T": "tc2072t18.glb",
    "TC|2084|T": "tc2084t18.glb",
    "TC|2090|T": "tc2090t18.glb",
    "TC|2096|T": "tc2096t18.glb",
    "TC|2436|T": "tc2436t20.glb",
    "TC|2448|T": "tc2448t20.glb",
    "TC|2460|T": "tc2460t20.glb",
    "TC|2472|T": "tc2472t20.glb",
    "TC|2484|T": "tc2484t20.glb",
    "TC|2490|T": "tc2490t20.glb",
    "TC|2496|T": "tc2496t20.glb",
    "TC|3036|T": "tc3036t26.glb",
    "TC|3048|T": "tc3048t26.glb",
    "TC|3060|T": "tc3060t26.glb",
    "TC|3072|T": "tc3072t26.glb",
    "TC|3084|T": "tc3084t26.glb",
    "TC|3090|T": "tc3090t26.glb",
    "TC|3096|T": "tc3096t26.glb",
    "TC|3648|T": "tc3648t26.glb",
    "TC|3660|T": "tc3660t26.glb",
    "TC|3672|T": "tc3672t26.glb",
    "TC|3684|T": "tc3684t26.glb",
    "TC|3690|T": "tc3690t26.glb",
    "TC|3696|T": "tc3696t26.glb",
    "TC|42120|TT": "tc42120tt34-3.glb",
    "TC|42144|TT": "tc42144tt34-3.glb",
    "TC|4260|TT": "tc4260tt34.glb",
    "TC|4272|TT": "tc4272tt34.glb",
    "TC|4284|TT": "tc4284tt34.glb",
    "TC|4290|TT": "tc4290tt34.glb",
    "TC|4296|TT": "tc4296tt34.glb",
    "TC|48120|TT": "tc48120tt36-3.glb",
    "TC|48144|TT": "tc48144tt36-3.glb",
    "TC|4860|TT": "tc4860tt36.glb",
    "TC|4872|TT": "tc4872tt36.glb",
    "TC|4884|TT": "tc4884tt36.glb",
    "TC|4890|TT": "tc4890tt36.glb",
    "TC|4896|TT": "tc4896tt36.glb",
    "TE|2448|X": "te2448x3236.glb",
    "TN|2030|T": "tn2030t18.glb",
    "TN|2430|T": "tn2430t20.glb",
    "TN|3030|T": "tn3030t26.glb",
    "TN|3630|T": "tn3630t26.glb",
    "TR|4020|TOS": "tr4020tos16-3.glb",
    "TR|4824|TOS": "tr4824tos16-3.glb",
    "TR|6030|TOS": "tr6030tos16-3.glb",
    "TZ|2448|T": "tz2448t18.glb",
    "TZ|2472|T": "tz2472t18.glb",
    "TZ|3060|T": "tz3060t22.glb",
    "TZ|3672|T": "tz3672t26.glb",
    "VW|2040|T": "vw2040t18.glb",
    "VW|2448|T": "vw2448t20.glb",
    "VW|3060|T": "vw3060t26.glb",
    "VW|3672|T": "vw3672t26.glb",
    "WG|45d36|GNT": "wg45d36gnt20.glb",
    "WG|60d30|GNT": "wg60d30gnt20.glb",
    "WG|60d36|GNT": "wg60d36gnt20.glb",
  },
};

/**
 * Look up the exact GLB filename for a series + shape + size + base combo.
 * Returns null if no model exists for that combination.
 */
export function lookupGlbFilename(
  seriesCode: string,
  shape: string,
  size: string,
  base: string,
): string | null {
  const seriesLookup = GLB_FILENAMES[seriesCode];
  if (!seriesLookup) return null;
  const key = `${shape.toUpperCase()}|${size}|${base.toUpperCase()}`;
  return seriesLookup[key] ?? null;
}

/**
 * Get shapes available for a series from the model availability map.
 */
export function getAvailableShapes(seriesCode: string): string[] {
  const series = MODEL_AVAILABILITY[seriesCode];
  if (!series) return [];
  return Object.keys(series.shapes);
}

/**
 * Get sizes available for a specific series + shape combo.
 */
export function getAvailableSizes(seriesCode: string, shapeCode: string): string[] {
  const series = MODEL_AVAILABILITY[seriesCode];
  if (!series) return [];
  return series.shapes[shapeCode]?.sizes ?? [];
}

/**
 * Get bases available for a specific series + shape combo.
 */
export function getAvailableBases(seriesCode: string, shapeCode: string): string[] {
  const series = MODEL_AVAILABILITY[seriesCode];
  if (!series) return [];
  return series.shapes[shapeCode]?.bases ?? [];
}

/**
 * Get the default hero GLB filename for a series.
 */
export function getDefaultGlb(seriesCode: string): string | undefined {
  return MODEL_AVAILABILITY[seriesCode]?.defaultGlb;
}

/**
 * Format a raw size code into a human-readable label.
 *
 * Rectangular sizes: "3060" -> '30" x 60"'
 * Round sizes (1-2 digits): "48" -> '48" Round'
 * Long tables (5 digits): "42120" -> '42" x 120"'
 * Special sizes like "3760" (Tapered): '37" x 60"'
 * Wedge/special: "45d36" -> '45" D36"'
 */
export function formatSizeLabel(raw: string): string {
  // Wedge-style sizes with "d" separator
  if (raw.includes("d")) {
    const parts = raw.split("d");
    return `${parts[0]}" x D${parts[1]}"`;
  }

  // Round tables (1-2 digit = just diameter)
  if (raw.length <= 2) {
    return `${raw}" Round`;
  }

  // 5-digit sizes: first 2 = width, rest = length (e.g., "42120" -> 42 x 120)
  if (raw.length === 5) {
    const w = raw.substring(0, 2);
    const l = raw.substring(2);
    return `${w}" x ${l}"`;
  }

  // Standard 4-digit: first 2 = width, last 2 = length
  if (raw.length === 4) {
    const w = raw.substring(0, 2);
    const l = raw.substring(2);
    return `${w}" x ${l}"`;
  }

  return raw;
}
