// 2026 TableX Base Series — authoritative marketing catalog.
//
// Source: "2026 Base Series Descriptions.docx" (Brian Craig, Apr 2026). Copy
// was generated by Brian against the Everyman / Outlaw archetype baseline.
//
// The legacy two-digit SKU codes in sku-registry.ts and product-catalog.json
// are PLACEHOLDER names from the initial seed phase (e.g. "Studio", "Nexus",
// "Alliance"). Use this catalog as the authoritative source of series identity;
// the `code` field maps to the legacy numeric code where known.
//
// Per Brian's Apr 15 email: Fundamental (code 33) will be rolled into
// Foundation as a no-cost option (plastic foot cap) rather than stand alone.

export type SeriesCode = string;

export interface SeriesEntry {
  /** Uppercase canonical name (e.g. "ULTRA", "FOUNDATION"). */
  slug: string;

  /** Display name (e.g. "Ultra", "VertiGO"). */
  name: string;

  /** Legacy two-digit code from sku-registry.ts, or null if unmapped. */
  code: SeriesCode | null;

  /** Short headline pulled from the marketing description. */
  headline: string;

  /** Full marketing paragraph. */
  description: string;

  /** Primary design traits / capabilities. */
  tags: string[];

  /** Photography / filter "Workspaces" from the Apr 2026 shot list. */
  workspaces: Workspace[];

  /** Photography / filter "Applications" from the Apr 2026 shot list. */
  applications: Application[];
}

export type Workspace =
  | "Workplace"
  | "Education"
  | "Hospitality"
  | "Healthcare"
  | "Outdoor";

export type Application =
  | "Training & Classroom"
  | "Café & Dining"
  | "Collaborative & Meeting"
  | "Occasional"
  | "Height-Adjustable"
  | "Nesting & Folding"
  | "Pull Up"
  | "Conference";

export const seriesCatalog: SeriesEntry[] = [
  {
    slug: "ULTRA",
    name: "Ultra",
    code: "00",
    headline: "Strong by design. Simple on purpose.",
    description:
      "Ultra focuses on what matters — a clean, open frame and a structure you can trust. It fits across private offices, open plans, and collaborative spaces without adding visual noise. It doesn’t try to do too much. It just does what it should — really well. Not everything needs to be overdesigned.",
    tags: ["clean frame", "private office", "open plan", "collaborative"],
    workspaces: ["Workplace", "Education", "Hospitality", "Healthcare"],
    applications: ["Training & Classroom", "Café & Dining", "Collaborative & Meeting", "Conference"],
  },
  {
    slug: "FOUNDATION",
    name: "Foundation",
    code: "30",
    headline: "The one everything else is built around.",
    description:
      "Foundation gets the essentials right. Strong. Reliable. Priced where it should be. Designed to handle a wide range of applications without overcomplicating the decision. It’s been a best seller for over 25 years for a reason. Because the basics should always be done right.",
    tags: ["best-seller", "reliable", "value", "versatile"],
    workspaces: ["Workplace", "Education", "Hospitality", "Healthcare"],
    applications: [
      "Training & Classroom",
      "Café & Dining",
      "Collaborative & Meeting",
      "Height-Adjustable",
      "Nesting & Folding",
      "Conference",
    ],
  },
  {
    slug: "STRETCH",
    name: "Stretch",
    code: "06",
    headline: "Not every space needs another straight line.",
    description:
      "Stretch was designed to break the pattern — just enough to change how a space feels without changing how it functions. That subtle arch isn’t just visual. It softens rows, improves flow, and creates a more natural rhythm in classrooms, training rooms, and multi-purpose spaces. Fully welded for strength. Built to handle daily use. Because better spaces aren’t always built on straight lines.",
    tags: ["arched", "welded", "classroom", "multi-purpose"],
    workspaces: ["Workplace", "Education", "Hospitality", "Healthcare"],
    applications: [
      "Training & Classroom",
      "Café & Dining",
      "Collaborative & Meeting",
      "Occasional",
      "Height-Adjustable",
      "Nesting & Folding",
    ],
  },
  {
    slug: "ELITE",
    name: "Elite",
    code: "08",
    headline: "There’s a difference between looking precise and being precise.",
    description:
      "Elite doesn’t cut corners — and it doesn’t pretend to. Laser-cut detailing. Fully welded construction. A complete line that delivers consistency without compromise. Eight base options. Zero guesswork. If it’s specified, it should perform exactly as expected.",
    tags: ["laser-cut", "welded", "precision", "complete line"],
    workspaces: ["Workplace", "Education", "Hospitality", "Healthcare"],
    applications: [
      "Training & Classroom",
      "Café & Dining",
      "Collaborative & Meeting",
      "Occasional",
      "Height-Adjustable",
      "Nesting & Folding",
      "Conference",
    ],
  },
  {
    slug: "REVEL",
    name: "Revel",
    code: null,
    headline: "Refinement, with a little more freedom.",
    description:
      "Revel brings a clean, elevated look to any environment — without overcomplicating the process. Its strength is in the details, especially when you start to make it your own. With the ability to specify two-tone base finishes at no additional cost, it’s easy to introduce contrast, highlight design intent, or keep things subtle and cohesive. Simple to specify. Easy to execute. Visually intentional. Because the right details shouldn’t come at a premium.",
    tags: ["two-tone", "refined", "design intent"],
    workspaces: ["Workplace", "Education"],
    applications: ["Training & Classroom", "Collaborative & Meeting", "Nesting & Folding"],
  },
  {
    slug: "APP",
    name: "App",
    code: null,
    headline: "Work doesn’t stay in one place. Neither should your table.",
    description:
      "App is built for mobility across spaces — home, office, and everywhere in between. Lightweight, adaptable, and easy to adjust, it supports the way people actually work today. No setup. No hassle. Just pick it up and go.",
    tags: ["mobile", "lightweight", "adaptable"],
    workspaces: ["Workplace", "Education", "Hospitality", "Healthcare"],
    applications: ["Training & Classroom", "Café & Dining", "Height-Adjustable", "Pull Up"],
  },
  {
    slug: "ELEMENT",
    name: "Element",
    code: null,
    headline: "One table. More environments.",
    description:
      "Element has always been about flexibility — lightweight, mobile, and easy to reconfigure. Now, it goes further. With the addition of ultra-durable powder coat finishes and solid surface tops, Element is ready for outdoor use without compromising the clean, refined look it’s known for indoors. Now it just works in more places — patios, terraces, open-air spaces — without requiring a different solution. Designed once. Used everywhere.",
    tags: ["mobile", "outdoor", "solid surface", "reconfigurable"],
    workspaces: ["Workplace", "Education", "Hospitality", "Healthcare", "Outdoor"],
    applications: [
      "Training & Classroom",
      "Café & Dining",
      "Collaborative & Meeting",
      "Occasional",
      "Nesting & Folding",
      "Conference",
    ],
  },
  {
    slug: "JUSTICE",
    name: "Justice",
    code: "40",
    headline: "Built to handle more.",
    description:
      "Justice is designed for strength where it matters most. A rigid frame and square column legs provide the stability needed for high-demand environments. Clean lines. Serious durability. No unnecessary extras. When it needs to hold up, it will.",
    tags: ["heavy-duty", "rigid frame", "square column"],
    workspaces: ["Workplace", "Education", "Hospitality", "Healthcare"],
    applications: ["Training & Classroom", "Café & Dining", "Collaborative & Meeting"],
  },
  {
    slug: "ARTISAN",
    name: "Artisan",
    code: null,
    headline: "Not everything needs to feel manufactured.",
    description:
      "Artisan brings warmth and material honesty into spaces that often feel overbuilt. Inspired by maker-style design, it pairs natural surfaces with a structure built to handle real use. Butcher block or laminate. Strength where it matters. Mobility when you need it. Craftsmanship — without sacrificing performance.",
    tags: ["butcher block", "maker-style", "warm"],
    workspaces: ["Workplace", "Education", "Hospitality"],
    applications: ["Training & Classroom"],
  },
  {
    slug: "PRIMARY",
    name: "Primary",
    code: "44",
    headline: "More options — without more complexity.",
    description:
      "Primary gives you the flexibility of multiple column and base combinations, while keeping the specification process straightforward. Round or square. Disc or column. Built to fit the space without slowing you down. Versatility, without the friction.",
    tags: ["multi-column", "disc", "versatile"],
    workspaces: ["Workplace", "Education", "Hospitality", "Healthcare"],
    applications: ["Training & Classroom", "Café & Dining", "Occasional", "Height-Adjustable"],
  },
  {
    slug: "PUDDLE",
    name: "Puddle",
    code: "45",
    headline: "Less structure. More intention.",
    description:
      "Puddle creates a softer, more grounded presence — designed to feel like it naturally belongs in the space. From lounge to bar height, with multiple adjustment options, it adapts quietly and effectively. Designed to blend in — done with purpose.",
    tags: ["lounge", "bar height", "soft"],
    workspaces: ["Workplace", "Education", "Hospitality", "Healthcare"],
    applications: ["Café & Dining", "Occasional", "Height-Adjustable"],
  },
  {
    slug: "EXCLAIM",
    name: "Exclaim",
    code: "71",
    headline: "Make the table part of the design — not an afterthought.",
    description:
      "Exclaim brings structure and presence into the room. Angled column bases create a bold visual foundation while supporting a wide range of modular configurations. It’s built to stand out — without disrupting everything around it. Confident design, exactly where it belongs.",
    tags: ["angled column", "modular", "statement"],
    workspaces: ["Workplace", "Hospitality"],
    applications: ["Occasional", "Conference"],
  },
  {
    slug: "VERTIGO",
    name: "VertiGO",
    code: "74",
    headline: "Freedom to move shouldn’t come with friction.",
    description:
      "VertiGO gives you full control — pneumatic, electric, or battery-powered height adjustment — paired with nesting capabilities that make reconfiguration effortless. Set it up. Move it around. Change it again tomorrow. Because flexible spaces shouldn’t feel complicated.",
    tags: ["height-adjustable", "pneumatic", "electric", "battery", "nesting"],
    workspaces: ["Workplace", "Education", "Healthcare"],
    applications: ["Training & Classroom", "Height-Adjustable", "Nesting & Folding"],
  },
  {
    slug: "SURGE",
    name: "Surge",
    code: "99",
    headline: "Light in profile. Strong in performance.",
    description:
      "Surge combines a thin visual footprint with adaptable functionality. From lounge to bistro height, it’s built to move with training, classroom, and collaborative environments. Clean, contemporary, and easy to work with. Design that stays out of the way — until it matters.",
    tags: ["thin profile", "bistro", "lounge", "adaptable"],
    workspaces: ["Workplace", "Education", "Hospitality", "Healthcare"],
    applications: [
      "Training & Classroom",
      "Café & Dining",
      "Collaborative & Meeting",
      "Occasional",
      "Height-Adjustable",
      "Nesting & Folding",
      "Conference",
    ],
  },
  {
    slug: "SOLO",
    name: "Solo",
    code: null,
    headline: "Built for focus. Designed for movement.",
    description:
      "Solo is made for the individual — but not for staying in one place. With smooth height adjustability, tilt-lock functionality, and mobility built in, it adapts to how work actually happens. Move it. Adjust it. Make it your own. Because focus doesn’t come from sitting still.",
    tags: ["individual", "height-adjustable", "tilt-lock", "mobile"],
    workspaces: ["Workplace", "Education", "Hospitality", "Healthcare"],
    applications: [
      "Training & Classroom",
      "Collaborative & Meeting",
      "Height-Adjustable",
      "Nesting & Folding",
      "Pull Up",
    ],
  },
  {
    slug: "TRIG",
    name: "Trig",
    code: null,
    headline: "Most “flexible” tables aren’t. This one is.",
    description:
      "Trig was built for real movement — not the kind that only works on paper. Adjust height. Flip. Nest. Move. Repeat. No workarounds hiding in the details. Battery-powered options. Tilt-lock surfaces. Mobility that actually performs in the field. If your space changes, Trig is already ahead of it.",
    tags: ["flip", "nest", "battery", "tilt-lock"],
    workspaces: ["Workplace", "Education"],
    applications: ["Training & Classroom", "Collaborative & Meeting", "Nesting & Folding"],
  },
];

export const seriesBySlug = new Map(seriesCatalog.map((s) => [s.slug, s]));
export const seriesByCode = new Map(
  seriesCatalog.filter((s) => s.code !== null).map((s) => [s.code!, s]),
);

export function getSeriesBySlug(slug: string): SeriesEntry | undefined {
  return seriesBySlug.get(slug.toUpperCase());
}

export function getSeriesByCode(code: string): SeriesEntry | undefined {
  return seriesByCode.get(code);
}

/** Series whose legacy numeric code is still unmapped — needs Brian's input. */
export const unmappedSeries: SeriesEntry[] = seriesCatalog.filter((s) => s.code === null);
